import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XU-SDE Dev",
  description: "This web app is generated by XU_SDE",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {/* <AuthProvider> */}
          <div className="min-h-screen max-w-[80%] p-5 m-auto flex flex-col justify-between">
            <Navbar />
            {children}
            <Footer />
          </div>
          {/* </AuthProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
